/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as UsersIdImport } from './routes/users/$id'
import { Route as UsersDetailsIndexImport } from './routes/users/details/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIdRoute = UsersIdImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRoute,
} as any)

const UsersDetailsIndexRoute = UsersDetailsIndexImport.update({
  id: '/users/details/',
  path: '/users/details/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/details/': {
      id: '/users/details/'
      path: '/users/details'
      fullPath: '/users/details'
      preLoaderRoute: typeof UsersDetailsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/$id': typeof UsersIdRoute
  '/users': typeof UsersIndexRoute
  '/users/details': typeof UsersDetailsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/$id': typeof UsersIdRoute
  '/users': typeof UsersIndexRoute
  '/users/details': typeof UsersDetailsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users/$id': typeof UsersIdRoute
  '/users/': typeof UsersIndexRoute
  '/users/details/': typeof UsersDetailsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/$id' | '/users' | '/users/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/$id' | '/users' | '/users/details'
  id: '__root__' | '/' | '/users/$id' | '/users/' | '/users/details/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersDetailsIndexRoute: typeof UsersDetailsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersDetailsIndexRoute: UsersDetailsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users/$id",
        "/users/",
        "/users/details/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users/$id": {
      "filePath": "users/$id.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/users/details/": {
      "filePath": "users/details/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
